version: "3"

set: ["nounset", "pipefail"]
shopt: ["globstar"]

includes:
  lint: "taskfiles/lint/main.yaml"
  docker-images: "taskfiles/docker-images/main.yaml"

vars:
  G_OUTPUT_DIR: "{{.ROOT_DIR}}/build"
  G_PROJECT_SRC_DIR: "{{.ROOT_DIR}}/src/log_archival_bench"

tasks:
  clean:
    cmds:
      - "rm -rf '{{.G_OUTPUT_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_OUTPUT_DIR}}'"
