FROM ubuntu:jammy AS base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    ca-certificates \
    checkinstall \
    curl \
    git \
    gpg \
    htop \
    jq \
    libcurl4 \
    libcurl4-openssl-dev \
    liblzma-dev \
    libmariadb-dev \
    libssl-dev \
    openjdk-11-jdk \
    pipx \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    rsync \
    software-properties-common \
    sqlite3 \
    tmux \
    unzip \
    vim
